name: Golden Path CD

on:
  push:
    branches:
      - "feature-*"
      - "release-*"
      - "hotfix-*"
      - main

permissions:
  actions: read
  contents: write
  pull-requests: read

jobs:
  delivery:
    name: Delivery
    if: github.event.created == false
    uses: JSL-Inc/golden-path-workflows-v2/.github/workflows/reusable-standard-cd.yml@v1.0.2a
    with:
      artifact_type: container
      deployment_provider: azure-container-apps
      deploy_command: bash scripts/aca-deploy.sh
      production_verify_command: bash scripts/production-verify.sh
    secrets: inherit

